# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGNpAbXOjLGYJCUmPQ_kS_d-Yh2hqUoN
"""

import secrets
import string

def generate_password(length, include_uppercase=True, include_lowercase=True, include_digits=True, include_special=True):
    characters = string.ascii_letters + string.digits + string.punctuation
    if not include_uppercase:
        characters = string.ascii_lowercase
    elif not include_lowercase:
        characters = string.ascii_uppercase
    if not include_digits:
        characters = ''.join(c for c in characters if not c.isdigit())
    if not include_special:
        characters = ''.join(c for c in characters if not c.isprintable() or c.isspace())

    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

# Take input from the user
length = int(input("Enter the length of the password: "))
while length < 12 or length > 20:
    print("Please choose a length between 12 and 20.")
    length = int(input("Enter the length of the password: "))

password = generate_password(length)
print(password)